### Creation of an Array

In [1]:
import numpy as np 

# different types of arrays

scalar = np.array(5)
vector = np.array([2,3,4])
matrix = np.array([[2,3,4],[5,6,7]])


print(scalar)
print(vector)
print(matrix)

5
[2 3 4]
[[2 3 4]
 [5 6 7]]


### Properties of an Array

In [5]:
arr = np.array([[2,4,6],[8,10,12]])

print("Dimention: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Dimention:  2
Shape:  (2, 3)
Size:  6
Data Type:  int64


### NumPy Built-In Functions

In [15]:
one = np.ones([2,3])
full = np.full([3,4], 7)
range = np.arange(1,11, 3)
print(one)
print(full)
print(range)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[ 1  4  7 10]


### Array Arithimetic Operations

In [3]:
import numpy as np
a = np.array([2,3,4])
b = np.array([4,5,6])

print("Sum: ", a + b)
print("Subtract", a - b)
print("Muliplication", a * b)
print("Division", a / b)



Sum:  [ 6  8 10]
Subtract [-2 -2 -2]
Muliplication [ 8 15 24]
Division [0.5        0.6        0.66666667]


### Array Comparisons Operations

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(b > a)
print(a == b)

[ True  True  True]
[False False False]


### Statistical Operations

In [8]:
x = np.array([2,6,8])
print(np.sum(x))
print(np.median(x), np.mean(x))
print(np.std(x))
print(np.max(x), np.min(x))


16
6.0 5.333333333333333
2.494438257849294
8 2


### Array Matrix Opeations

In [ ]:
a = np.array([[2,3,5],
                [5,6,7]])
A = a.T
b = np.array([[8,1,0],
                [1,3,5]])
print(A)

# Cross product is only for 3D vectors, not matrices.
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

cross = np.cross(a, b)
dot = np.dot(a,b)
print(dot)
print(cross)


x = np.array([
            [1,3,3],
            [1,3,4],
            [1,4,3]
        ])
print(np.linalg.det(x))
print(np.linalg.inv(x))



[[2 5]
 [3 6]
 [5 7]]
56
[-3  6 -3]
-1.0
[[ 7. -3. -3.]
 [-1.  0.  1.]
 [-1.  1.  0.]]
