### Creation of an Array

In [1]:
import numpy as np 

# different types of arrays

scalar = np.array(5)
vector = np.array([2,3,4])
matrix = np.array([[2,3,4],[5,6,7]])


print(scalar)
print(vector)
print(matrix)

5
[2 3 4]
[[2 3 4]
 [5 6 7]]


### Properties of an Array

In [5]:
arr = np.array([[2,4,6],[8,10,12]])

print("Dimention: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Dimention:  2
Shape:  (2, 3)
Size:  6
Data Type:  int64


### NumPy Built-In Functions

In [12]:
one = np.ones([2,3])
full = np.full([3,4], 7)
range = np.arange(1,11, 2)
print(one)
print(full)
print(range)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[1 3 5 7 9]
